// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUVR-12IcR0iPRwTtsvcvMtHs9mgj93GA',
    appId: '1:815893673486:web:38e6853d444d195619ee5f',
    messagingSenderId: '815893673486',
    projectId: 'tripmatedev-919d3',
    authDomain: 'tripmatedev-919d3.firebaseapp.com',
    storageBucket: 'tripmatedev-919d3.firebasestorage.app',
    measurementId: 'G-H0K93KL0PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmYCwOugkVm1dEtL5hVsrQP3IpW8cvwKI',
    appId: '1:815893673486:android:cdfe8afaba380a3b19ee5f',
    messagingSenderId: '815893673486',
    projectId: 'tripmatedev-919d3',
    storageBucket: 'tripmatedev-919d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg1fg33Wy94tOov-R0fGSbwBgxlRYPgj4',
    appId: '1:815893673486:ios:784c11a666fdc21719ee5f',
    messagingSenderId: '815893673486',
    projectId: 'tripmatedev-919d3',
    storageBucket: 'tripmatedev-919d3.firebasestorage.app',
    iosBundleId: 'com.example.tripmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg1fg33Wy94tOov-R0fGSbwBgxlRYPgj4',
    appId: '1:815893673486:ios:784c11a666fdc21719ee5f',
    messagingSenderId: '815893673486',
    projectId: 'tripmatedev-919d3',
    storageBucket: 'tripmatedev-919d3.firebasestorage.app',
    iosBundleId: 'com.example.tripmate',
  );
}
